blog/urls.py
from django.urls import path
from blog.views import (IndexView, PostDetailView, CategoryListView, TagListView,
	CategoryPostView, TagPostView, SearchPostView)

app_name = 'blog'
urlpatterns = [
	path('', IndexView.as_view(), name='root'),
	path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
	path('categories/', CategoryListView.as_view(), name='category_list'),
	path('tags/', TagListView.as_view(), name='tag_list'),
	path('category/<str:category_slug>/', CategoryPostView.as_view(), name='category_post'),
	path('tag/<str:tag_slug>/', TagPostView.as_view(), name='tag_post'),
	path('search/', SearchPostView.as_view(), name='search_post'),
]

dbsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('markdownx/', include('markdownx.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	

blog/models.py
from django.db import models
from django.db.models import Count
from django.utils import timezone
from markdownx.models import MarkdownxField
# Create your models here.


class Category(models.Model):
	name = models.CharField(max_length=255)
	slug = models.SlugField(unique=True)
	timestamp = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.name

class Tag(models.Model):
	name = models.CharField(max_length=255)
	slug = models.SlugField(unique=True)
	timestamp = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.name




class Post(models.Model):
	category = models.ForeignKey(Category, on_delete=models.PROTECT)
	tags = models.ManyToManyField(Tag, blank=True)
	title = models.CharField(max_length=255)
	content = MarkdownxField('content', help_text="マークダウンで記述")
	description = models.TextField(blank=True)
	image = models.ImageField(
		upload_to='post_images/', null=True, blank=True
	)
	created_at = models.DateTimeField(auto_now_add=True)
	published_at = models.DateTimeField(blank=True, null=True)
	is_public = models.BooleanField(default=False)


	class Meta:
		ordering = ['-created_at']

	def save(self, *args, **kwargs):
		if self.is_public and not self.published_at:
			self.published_at = timezone.now()
		super().save(*args, **kwargs)

	def __str__(self):
		return self.title

blog/views.py
from django.shortcuts import render
from django.db.models import Count, Q
from django.http import Http404
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.shortcuts import get_object_or_404

from blog.models import Post, Category, Tag


class PostDetailView(DetailView):
	model = Post 

	def get_object(self, queryset=None):
		obj = super().get_object(queryset=queryset)
		if not obj.is_public and not self.request.user.is_authenticated:
			raise Http404
		return obj

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		return context

class IndexView(ListView):
	paginate_by = 10
	model = Post 
	template_name = 'blog/index.html'

class SearchPostView(ListView):
	paginate_by = 10
	model = Post
	template_name = "blog/search_post.html"

	def get_queryset(self):
		print("hello")
		query = self.request.GET.get('q')
		lookups = (
			Q(title__icontains=query) |
			Q(content__icontains=query) |
			Q(category__name__icontains=query) |
			Q(tags__name__icontains=query)
		)
		if query:
			qs = Post.objects.filter(lookups).distinct()
			return qs
		qs=super().get_queryset.filter()
		return qs

	def get_context_data(self, **kwargs):
		context=super().get_context_data(**kwargs)
		query = self.request.GET.get('q')
		context['query'] = query
		return context 

class CategoryListView(ListView):
	queryset = Category.objects.annotate(
		num_posts=Count('post', fliter=Q(post__is_public = True)))

class TagListView(ListView):
	queryset = Tag.objects.annotate(num_posts = Count('post', filter=Q(post__is_public=True))).order_by("-num_posts")


class CategoryPostView(ListView):
	paginate_by = 10
	model = Post
	template_name = 'blog/category_post.html'

	def get_queryset(self):
		category_slug = self.kwargs['category_slug']
		self.category = get_object_or_404(Category, slug=category_slug)
		qs = super().get_queryset().filter(category=self.category)
		return qs
	
	def get_context_data(self,**kwargs):
		context = super().get_context_data(**kwargs)
		context['category'] = self.category
		return context 

class TagPostView(ListView):
	paginate_by = 10
	model = Post
	template_name = 'blog/tag_post.html'

	def get_queryset(self):
		tag_slug = self.kwargs['tag_slug']
		self.tag = get_object_or_404(Tag, slug=tag_slug)
		qs = super().get_queryset().filter(tags=self.tag)
		return qs

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['tag'] = self.tag 
		return context

blog/templates/blog/base.html
<!-- templates/base.html -->

{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}MyBlog{% endblock %}</title>
    <meta name="description" content="{% block description %}{% endblock %}">

    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
  </head>
  <body>
    {% include 'blog/base/navbar.html' %}
    {% block content %}
    {% endblock %}

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="{% static 'blog/js/blog.js'%}"></script>

    <!-- highlight.js -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.2/styles/dracula.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.2/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
  </body>
</html>

blog/templates/blog/base/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'blog:root' %}">SK Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav ml-auto">
      {% include "blog/snippets/search_form.html" %}
    </div>
  </div>

</nav>

blog/templates/blog/category_list.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}カテゴリ一覧 | {{ block.super }}{% endblock %}
{% block description %}カテゴリーの一覧です。好きなカテゴリーに飛べます{% endblock %}

{% block content %}

<h1>カテゴリ一覧</h1>
<ul>
	{% for category in object_list %}
	<li><a href="{% url 'blog:category_post' category.slug %}">{{ category.name }} ({{ category.num_posts }})</a></li>
	{% empty %}
	<li>カテゴリはありません</li>
	{% endfor %}
</ul>

{% endblock %}

blog/templates/blog/category_post.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}{{ category.name }}の投稿 | {{ block.super }}{% endblock %}
{% block description %}{{ category.name }}の投稿の一覧です{% endblock %}

{% block content %}

<h1>「{{ category.name }}」の投稿一覧</h1>
<div class="row category-post-view">
  {% for post in page_obj %}
  <div class="col-md-6 col-lg-4">
		<a href="{% url 'blog:post_detail' post.id %}">
			<div class="card shadow bg-white rounded">
				{%if post.image %}
					<img src="{{ post.image.url }}" alt="{{ post.title }}" class="main-post-img">
				{% else %}
					<img src="{% static 'img/unnamed.png'%}" class="main-post-img">
				{% endif %}
				<div class="card-body">
					<h5 class="card-title">	{% if user.is_authenticated or post.is_public %}
  {% if not post.is_public %}[下書き] {% endif %}{{ post.title }}
  {% endif %}</h5>
					<p class="card-text"> {{ post.description|truncatechars:30 }}</p>
				</div>
			</div>
		</a>
	</div>
  {% empty %}
  <h1>No Post</h1>
  {% endfor %}
 </div>

{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}投稿一覧 | {{ block.super}} {% endblock %}
{% block description %}マイブログです。プログラミング学習の経過をこちらに記します{%endblock%}





{% block content %}
<div class="container main-box">
	<div class="row">
		<div class="col-md-8">
			{% include "blog/snippets/main_post_list.html" %}
		</div>
		<aside calss="col-md-4">
			{% include "blog/snippets/sidebar.html" %}
		</aside>
	</div>
</div>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% load app %}

{% block title %}投稿詳細 | {{ block.super }} {% endblock %}
{% block description %} {{ object.title}}の詳細画面です {% endblock %}

{% block content %}
<div class="post-detail">


<div class="col-12">
	<div class="content-box">
		<h1 >{{ object.title }}</h1>
		<p>{{ object.published_at|date }}</p>
		<p><a href="{% url 'blog:category_post' object.category.slug%}" class="btn btn-outline-secondary">{{ object.category.name }}</a></p>
		{% for tag in object.tags.all %}
		<a href="{% url 'blog:tag_post' tag.slug%}" class="btn btn-light">{{ tag.name }}</a>
		{% endfor %}
		<hr>
		<div class="post-content">
			{{ object.content|markdown_to_html }}
			{% for photo in photos %}
			<img src="{{ photo.content_image.url }}" width="300" height="200">
		</div>
		{% endfor %}
	</div>
</div>


</div>
{% endblock %}

blog/templates/blog/search_post.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %} {% if query %}{{query}}{% endif %} | {{ block.super}} {% endblock %}
{% block description %}{% if query %}{{query}}の検索結果です{% else %}投稿一覧です{% endif %}{%endblock%}





{% block content %}

<div class="container main-box">
	<div class="row">
		<div class="col-md-8">
			<h1>「{% if query %}{{query}}{% endif %}」の検索結果</h1>
			<p>{{ page_obj.start_index }}-{{ page_obj.end_index}}件 ({{ paginator.count }}件)</p>
			{% include "blog/snippets/main_post_list.html" %}
			{% include "blog/snippets/pagination.html" %}
		</div>
		<aside calss="col-md-4">
			{% include "blog/snippets/sidebar.html" %}
		</aside>
	</div>
</div>

{% endblock %}

blog/templates/blog/snippets/main_post_list.html
{% load static %}
{% load app %}

<div class="row">

{% for post in page_obj %}
{% if post.is_public %}
	<div class="col-md-6 col-lg-4">
		<a href="{% url 'blog:post_detail' post.id %}">
			<div class="card shadow bg-white rounded">
				{%if post.image %}
					<img src="{{ post.image.url }}" alt="{{ post.title }}" class="main-post-img">
				{% else %}
					<img src="{% static 'img/unnamed.png'%}" class="main-post-img">
				{% endif %}
				<div class="card-body">
					<h5 class="card-title">{{ post.title|truncatechars:30 }}</h5>
				</div>
			</div>
		</a>
	</div>
{% endif %}
{%endfor%}
</div>

blog/templates/blog/snippets/pagination.html
{% if is_paginated %}

<nav>
	{% if page_obj.has_previous %}
	<a href="?page={{ page_obj.previou_page_number }}{% if query %}&q={{query}}{% endif %}">前へ</a>
	{% endif %}

	{% for num in paginator.page_range %}
	{% if page_obj.number == num %}
	<span> {{ num }} </span>
	{% else %}
	<a href="?page={{ num }}{% if query %}&q={{query}}{% endif %}">{{ num }}</a>
	{% endif %}
	{% endfor %}

	{% if page_obj.has_next %}
	<a href="?page={{ page_obj.next_page_number }}{% if query %}&q={{query}}{% endif %}">次へ</a>
	{% endif %}
</nav>

{% endif %}

blog/templates/blog/snippets/search_form.html
<form class="form-inline" action="{% url 'blog:search_post' %}" >
  <input class="form-control" type="text" placeholder="Search" aria-label="Search" name="q" value="{{ request.GET.q }}">
  <button type="submit" class="btn btn-success">検索</button>
</form>

blog/templates/blog/snippets/sidebar.html
<div class="card mb-3">
  <div class="card-header">
    カテゴリ
  </div>
  <ul class="list-group list-group-flush">
    {% for category in categories|dictsort:"id" %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <a href="{% url 'blog:category_post' category.slug %}" class="card-link">{{ category.name }}</a>
      <span class="badge badge-primary badge-pill">{{ category.num_posts }}</span>
    </li>
    {% endfor %}
  </ul>
</div>

<div class="card">
  <div class="card-header">
    タグ
  </div>
  <ul class="list-group list-group-flush">
    {% for tag in tags|slice:":5" %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <a href="{% url 'blog:tag_post' tag.slug %}" class="card-link">{{ tag.name|truncatechars:12 }}</a>
      <span class="badge badge-primary badge-pill">{{ tag.num_posts }}</span>
    </li>
    {% endfor %}
  </ul>
  <div class="card-body text-center">
    <a href="{% url 'blog:tag_list' %}" class="card-link">すべてのタグを見る</a>
  </div>
</div>

blog/templates/blog/tag_list.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}タグ一覧 | {{ block.super }} {%endblock%}

{% block content %}


<h1>タグ一覧</h1>
<ul>
	{% for tag in object_list%}
	<li><a href="{% url 'blog:tag_post' tag.slug %}">{{ tag.name }}({{ tag.num_posts}})</a></li>
	{% empty %}
	<li>タグはありません</li>
	{% endfor %}
</ul>

{%endblock%}

blog/templates/blog/tag_post.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}{{ tag.name }}の投稿一覧 | {{block.super}}{%endblock%}
{% block description %}{{ tag.name }}の投稿の一覧です {%endblock%}

{% block content %}

<h1>「#{{ tag.name }}」の投稿一覧</h1>
<div class="row category-post-view">
  {% for post in page_obj %}
  <div class="col-md-6 col-lg-4">
		<a href="{% url 'blog:post_detail' post.id %}">
			<div class="card shadow bg-white rounded">
				{%if post.image %}
					<img src="{{ post.image.url }}" alt="{{ post.title }}" class="main-post-img">
				{% else %}
					<img src="{% static 'img/unnamed.png'%}" class="main-post-img">
				{% endif %}
				<div class="card-body">
					<h5 class="card-title">	{% if user.is_authenticated or post.is_public %}
  {% if not post.is_public %}[下書き] {% endif %}{{ post.title }}
  {% endif %}</h5>
					<p class="card-text"> {{ post.description|truncatechars:30 }}</p>
				</div>
			</div>
		</a>
	</div>
  {% empty %}
  <h1>No Post</h1>
  {% endfor %}
 </div>

{%endblock%}